1- Create three lists representing house features, each list containing ten values. The first one for the house's size in square meters, the second one for rooms and last for price. Then, create an array combining these lists.

In [57]:
import numpy as np

size = [100, 120, 80, 150, 200, 90, 110, 130, 180, 95]
rooms = [2, 3, 2, 4, 5, 2, 3, 3, 4, 2]
price = [200000, 250000, 180000, 350000, 450000, 190000, 220000, 260000, 400000, 195000]

houses = np.array([size, rooms, price])
print(houses)

[[100 120 80 150 200 90 110 130 180 95]
 [2 3 2 4 5 2 3 3 4 2]
 [200000 250000 180000 350000 450000 190000 220000 260000 400000 195000]]


2- Transpose the array you have created, so that every line can represent features of one house.

In [58]:
transposed_houses = houses.transpose()
transposed_houses

array([[100, 2, 200000],
       [120, 3, 250000],
       [80, 2, 180000],
       [150, 4, 350000],
       [200, 5, 450000],
       [90, 2, 190000],
       [110, 3, 220000],
       [130, 3, 260000],
       [180, 4, 400000],
       [95, 2, 195000]])

3- Display the shape of the array and explain what it means.

In [59]:
transposed_houses.shape

(10, 3)

means 10 rows and 3 columns , one row for each house

For the following assignment, you are going to use Earthquakes dataset.

4- Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.

In [60]:
#set current workind directory
import os
cwd = os.getcwd()
cwd

'/home/monkeyrampage/Desktop/Magnimind/Assignments'

In [61]:
os.chdir('/home/monkeyrampage/Desktop/Magnimind/Intro_to_Python/datasets')

In [62]:
earthquake_data = np.genfromtxt('earthquakes1970-2014.csv', delimiter=',')

In [63]:
earthquake_data.shape

(5305, 12)

In [64]:
os.chdir(cwd)

In [65]:
os.getcwd()
#get back where we are working

'/home/monkeyrampage/Desktop/Magnimind/Assignments'

5- Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

In [66]:
# I also added depth column
sliced_data = earthquake_data[:20, [2,3,4,5,6,11]]
sliced_data[np.isnan(sliced_data)] = 0
sliced_data = sliced_data.astype(int)
sliced_data

array([[0, 0, 0, 0, 0, 0],
       [102, 31, 7, 0, 90, 1970010440],
       [151, 8, 6, 0, 85, 1970010640],
       [178, 179, 6, 0, 59, 1970010840],
       [126, 73, 6, 0, 91, 1970011040],
       [-152, 85, 6, 0, 0, 0],
       [-177, 80, 6, 0, 175, 1970012040],
       [142, 46, 6, 0, 199, 1970012040],
       [-104, 33, 6, 0, 140, 1970012140],
       [166, 50, 6, 0, 91, 1970012640],
       [-99, 21, 6, 0, 100, 1970020440],
       [122, 11, 6, 0, 94, 1970020540],
       [100, 33, 6, 0, 57, 1970020640],
       [103, 33, 6, 0, 94, 1970022440],
       [-179, 7, 6, 0, 0, 0],
       [-175, 161, 6, 0, 0, 0],
       [143, 33, 6, 0, 82, 1970030440],
       [168, 41, 6, 0, 61, 1970030940],
       [148, 40, 6, 0, 65, 1970031040],
       [-153, 16, 6, 0, 0, 0]])

6- Display the row numbers where last values are equal to 4.5 or higher.

In [67]:
last_column = earthquake_data[:, -1]
matching_rows = np.where(last_column >= 4.5)[0]

print(matching_rows)
matching_rows.shape

[1 2 3 ... 5302 5303 5304]


(5242,)

7- Assign 1 to first row.

In [74]:
# Assign 1 to the first row
earthquake_data[0, :] = 1
#earthquake_data[:1,:]

8- Save the final state of the array to disk. You are going to use this in the next assignment.

In [75]:
earthquake_data[np.isnan(earthquake_data)] = 0
earthquake_data = earthquake_data.astype(int)
np.savetxt('modified_earthquake_data.csv', earthquake_data, delimiter=',')

9- Load the array you saved in the previous lesson from the disk.

In [78]:
loaded_modified_data = np.loadtxt('modified_earthquake_data.csv', delimiter=',')
loaded_modified_data.shape

(5305, 12)

10- Display the mean and the standard deviation for each column.

In [81]:
means = np.mean(loaded_modified_data, axis=0)
stds = np.std(loaded_modified_data, axis=0)
means , stds

(array([1.88501414e-04, 2.63543827e+00, 4.44880302e+01, 7.40976437e+01,
        6.10574929e+00, 1.88501414e-04, 2.98645429e+02, 1.59208294e+00,
        2.11875589e-01, 4.59189444e-01, 1.88501414e-04, 1.95679169e+09]),
 array([1.37282876e-02, 2.94589954e+01, 1.24326742e+02, 1.28999096e+02,
        3.36773695e-01, 1.37282876e-02, 1.72779183e+02, 1.28758830e+01,
        2.13546207e+00, 5.93622168e-01, 1.37282876e-02, 2.72896144e+08]))

11- Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be dobe in one line of code.)

In [82]:
subtractions = np.array([1, 25, 25, 10, 4])
loaded_modified_data -= subtractions

ValueError: operands could not be broadcast together with shapes (5305,12) (5,) (5305,12) 

12- Multiply each element by 2. (Remember it can be done in one line of code.)


*Please add the URL of the assignments you uploaded to Github to the Online Text section

In [34]:
import os
from shutil import copy2

In [35]:
home_path = os.path.expanduser('~')    
git_dir = os.path.join(home_path, "git")
course_dir = os.path.join(git_dir, "Magnimind")
submission_dir = os.path.join(course_dir, "Assignments")
submission_dir

'/home/monkeyrampage/git/Magnimind/Assignments'

In [36]:
cwd = os.getcwd()
cwd

'/home/monkeyrampage/Desktop/Magnimind/Assignments'

In [37]:
error = False

if not os.path.exists(git_dir):
    print("git directory {} does not exist. Make sure you set git up correctly".format(git_dir))
    error = True
elif not os.path.exists(course_dir):
    print("Course's git repository does not exist under the git directory.")
    print("Make sure it is created as folder {}".format(course_dir))
    error = True
elif not os.path.exists(submission_dir):
    print("\"Submissions\" directory does not exist. Creating it...")
    os.makedirs(submission_dir)

if not error:
    print("Everything is ready for submission")
else:
    assert("There were errors. Please fix them before proceeding!")

Everything is ready for submission


### Define the course and the assignment name down below: (Be careful!)

In [1]:
# CHANGE THIS CELL BEFORE EVERY ASSIGNMENT
course_name = "Intro_Python_"
assignment_name = "NumpyAssignment"

In [39]:
assignment_name = course_name + assignment_name
assignment_name

'Intro_Python_StringAssignment'

In [40]:
files_to_be_copied = [assignment_name+".ipynb"]

if not error:
    for filename in files_to_be_copied:
        print("Copying file {} to {}".format(filename, submission_dir))
        copy2(filename, submission_dir)
        os.chdir(submission_dir)
        git_add_command = "git add {}".format(filename)
        print(git_add_command)
        os.system(git_add_command)
        os.chdir(cwd)
    print("Submitting solution files for assignment: {}".format(assignment_name))
    os.chdir(submission_dir)
    git_commit_command = "git commit -m \"Solution files for assignment: {} added\"".format(assignment_name)
    print(git_commit_command)
    os.system(git_commit_command)
    git_push_command = "git push origin main"
    print(git_push_command)
    os.system(git_push_command)
    os.chdir(cwd)
    print("Done submitting solution files for assignment: {}".format(assignment_name))

Copying file Intro_Python_StringAssignment.ipynb to /home/monkeyrampage/git/Magnimind/Assignments
git add Intro_Python_StringAssignment.ipynb
Submitting solution files for assignment: Intro_Python_StringAssignment
git commit -m "Solution files for assignment: Intro_Python_StringAssignment added"
[main 5d8793c] Solution files for assignment: Intro_Python_StringAssignment added
 1 file changed, 355 insertions(+)
 create mode 100644 Assignments/Intro_Python_StringAssignment.ipynb
git push origin main
Done submitting solution files for assignment: Intro_Python_StringAssignment


To github.com:monkeyrampage/Magnimind.git
   2970ff0..5d8793c  main -> main
